security:
    encoders:
        AppBundle\Entity\User:      plaintext

    providers:
        default:
            entity:                 { class: AppBundle:User }

    firewalls:
        api_oauth2_implicite:
            pattern:                ^/api/oauth2/implicit$
            http_basic:             ~
            provider:               default

        api_oauth2_authorize:
            pattern:                ^/api/oauth2/authorize$
            http_basic:             ~
            provider:               default

        api_oauth2_token:
            pattern:                ^/api/oauth2/token$
            oauth2_token:           ~

        api_storage:
            pattern:                ^/api/storage
            oauth2_resource:        ~
