services:
    app.remote_storage:
        class: AppBundle\RemoteStorage\RemoteStorage
        arguments: ['@app.metadata_storage', '@app.document_storage']

    app.metadata_storage:
        class: AppBundle\RemoteStorage\DoctrineMetadataStorage
        arguments: ['@doctrine.orm.entity_manager']

    app.document_storage:
        class: AppBundle\RemoteStorage\FileDocumentStorage
        arguments: ['%kernel.root_dir%/../var/documents']
